### ISSUE TITLE
AssertionError: unknown api type helm.

### ISSUE THREAD

**Issue by zengya55** [hengyuan-hu/instruct-rl#1]
when I run python openai_api.py, it turns out that:
`num prompts: 3852
loading cache from /home/yzeng/pyhanabi/openai/dev_cache.pkl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3852/3852 [00:00<00:00, 136418.56it/s]
All match? True
num mismatch: 0
loading cache from /home/yzeng/pyhanabi/openai/dev_cache.pkl
  0%|                                                                                                                                   | 0/3852 [00:00<?, ?it/s]Error encountered, saving cache
unknown api type helm.
Error encountered, saving cache
unknown api type helm.
Error encountered, saving cache
  0%|                                                                                                                                   | 0/3852 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yzeng/instruct-rl/pyhanabi/openai_api.py", line 389, in <module>
    hist_move_logit = generate_full_prior(
  File "/home/yzeng/instruct-rl/pyhanabi/openai_api.py", line 361, in generate_full_prior
    results = evaluate_yes_or_no(prompts, cache_file=cache_file, api_type="helm")
  File "/home/yzeng/instruct-rl/pyhanabi/openai_api.py", line 301, in evaluate_yes_or_no
    raise e
  File "/home/yzeng/instruct-rl/pyhanabi/openai_api.py", line 292, in evaluate_yes_or_no
    assert False, f"unknown api type {api_type}."
AssertionError: unknown api type helm.`
 I wonder why it uses the api_type "helm".

**Comment by hengyuan-hu** [comment]
Thanks for catching this. The api_type at `line 358` should be `openai`. I just updated the code.
