### ISSUE TITLE
The R2D2 agent not learning with any max_len value other than 80.

### ISSUE THREAD

**Issue by hnekoeiq** [hengyuan-hu/instruct-rl#2]
Hi @hengyuan-hu,

Thanks for your great repo.
I was trying to reproduce some baselines and I faced an issue. Even though r2d2 agent learns successfuly with the defaul `max_len=80`, trying any other `max_len` results in almost zero score even after the training completes. 

Any idea what could be the isse?

**Comment by hengyuan-hu** [comment]
What max_len do you use? Do you load a pretrained model or train from scratch?

**Comment by hnekoeiq** [comment]
I tried several values like 40, 20, and 10.

No, training from scratch.

**Comment by hengyuan-hu** [comment]
That's too short. The games are forced to terminated with 0 reward. https://github.com/hengyuan-hu/instruct-rl/blob/bc3827eba352b69646e15fe4415971cd6ed4fdb6/cpp/utils.cc#L13

I tried 75, 80, and 90 and it works fine. So this is probably not a bug in the data format or anything. If you want to train shorter games, you need to modify the game definition.

**Comment by hnekoeiq** [comment]
I see.
I was under the impression that `max_len` is just he length of trajectory stored in the buffer and it does not change the episode length. 

Thanks for clarification.
